export const courseData = [
  {
    id: 1,
    title: "The Complete 2022 Web Development Camp One",
    slug: "the-complete-2022-web-development-camp-one",
    description: "The Complete 2022 Web Development Camp",
    details: "",
    youtube_playlist_id: "UU0fQiGRmQuOjj_o_FoAH05A",
    image: "/images/course/course-thumb-01.jpg",
    course_type: "free",
    price: "100",
    sale_price: "80",
    total_student: "100+",
    total_reviews: "300+",
    total_ratings: "100",
    total_stars: "4.7",
  },
  {
    id: 2,
    title: "The Complete 2022 Web Development Camp Two",
    slug: "the-complete-2022-web-development-camp-two",
    description: "The Complete 2022 Web Development Camp",
    details: "",
    youtube_playlist_id: "",
    image: "/images/course/course-thumb-02.jpg",
    course_type: "paid",
    price: "100",
    sale_price: "80",
    total_student: "100+",
    total_reviews: "300+",
    total_ratings: "100",
    total_stars: "4.7",
  },
  {
    id: 3,
    title: "The Complete 2022 Web Development Camp Three",
    slug: "the-complete-2022-web-development-camp-three",
    description: "The Complete 2022 Web Development Camp",
    details: "",
    youtube_playlist_id: "UU0fQiGRmQuOjj_o_FoAH05A",
    image: "/images/course/course-thumb-03.jpg",
    course_type: "free",
    price: "100",
    sale_price: "80",
    total_student: "100+",
    total_reviews: "300+",
    total_ratings: "100",
    total_stars: "4.7",
  },

  {
    id: 4,
    title: "The Complete 2022 Web Development Camp Four",
    slug: "the-complete-2022-web-development-camp-four",
    description: "The Complete 2022 Web Development Camp",
    details: "",
    youtube_playlist_id: "",
    image: "/images/course/course-thumb-04.jpg",
    course_type: "free",
    price: "100",
    sale_price: "80",
    total_student: "100+",
    total_reviews: "300+",
    total_ratings: "100",
    total_stars: "4.7",
  },
  {
    id: 5,
    title: "The Complete 2022 Web Development Camp Five",
    slug: "the-complete-2022-web-development-camp-five",
    description: "The Complete 2022 Web Development Camp",
    details: "",
    youtube_playlist_id: "",
    image: "/images/course/course-thumb-01.jpg",
    course_type: "paid",
    price: "100",
    sale_price: "80",
    total_student: "100+",
    total_reviews: "300+",
    total_ratings: "100",
    total_stars: "4.7",
  },
];
